### PR TITLE
Logo updates, website is now responsive and minor fix (#6)

### PR DESCRIPTION
**Pull request by sourabhtk37**
- Website is responsive now
- New logo added

Contribution by @realslimshanky. Updated site sample [here](https://realslimshanky.github.io/ILUG-D.github.io/)

Will merge to `master` once consensus on new logo is reached. Add thumbs-up to this comment if you like the new logo:
logo

### CODE REVIEW

**Comment by realslimshanky** [comment]
@sourabhtk37 , you might wanna look into this it's been long overdue.

**Comment by sourabhtk37** [comment]
I am ready to merge but without consensus I can't @realslimshanky

**Comment by realslimshanky** [comment]
Oh sorry, I meant to tag  @mysticTot

**Comment by rajudev** [comment]
@realslimshanky Thanks for all your efforts and making the changes to the website. Just a request. Whenever you make changes to any source code, add each change to a separate commit. Its a good practice and improves readability for the reviewer of pull requests. 
So whenever you change a single file. add the change for it to a commit. You do not need to push after every commit. Once you are done with all your changes, then push your changes. All your commits will come in a single git push.

**Comment by sourabhtk37** [comment]
@rajudev I squashed those commits when reviewing his previous PR. This was a single commit issue and reviews created more non-useful commits. That's why squashed.

**Comment by realslimshanky** [comment]
@rajudev sure, I'll keep that in mind.
@sourabhtk37, thanks for taking care of this. :)

**Pull request merged**
