### PR TITLE
Adding ILUG-D meme channel link

### PR DESCRIPTION
**Pull request by miphilomath**
Solving #60

### CODE REVIEW

**Comment by nk521** [comment]
Do we really need this?

**Comment by hellozee** [comment]
Instead of a link, I think a gallery would be good, but that would be a PITA to maintain.

**Comment by miphilomath** [comment]
> Instead of a link, I think a gallery would be good, but that would be a PITA to maintain.
Agreed, so we put few of the memes in the gallery section and put the link there, so that we won't have to worry about maintaining frequently. Thus, closing this pull request and the issue associated.

**Comment by miphilomath** [comment]
> Do we really need this?

We didn't need the meme channel either, but it was a great idea :D

**Pull request closed without merging**
