### PR TITLE
Add contribution guidelines

### LINKED ISSUE #21: Add contribution guidelines

### PR DESCRIPTION
**Pull request by mundane140**
- Fixes #21 
Need suggestions.

### CODE REVIEW

**Comment by mundane140** [comment]
@hellozee

**Comment by miphilomath** [comment]
LGTM @mundane140 
Please update the license in the commit and add a note to update Change Log for every major change in the code.

**Comment by mundane140** [comment]
Its been a while. Let's see...

**Comment by mundane140** [comment]
I have added suggested changes. Requesting a review @miphilomath

**Comment by hellozee** [comment]
LGTM

**Pull request merged**
