### PR TITLE
Volunteers page (Work in Progress)

### LINKED ISSUE #37: Add a volunteers section to our webpage.
For the format of the volunteer's section, take a look at this
https://github.com/ILUGD/Suggestions/issues/3

### PR DESCRIPTION
**Pull request by akshay-nm**
- Adds a new page for Volunteers
- Based on ILUGD/Suggestions#3
- Fixed #37 

Why work in progress? 
Its a template with dummy data. Need actual content in order to be merged.

### CODE REVIEW

**Comment by mundane140** [comment]
Here is what it looks like at the moment.
Screenshot from 2019-06-22 13-10-42
Screenshot from 2019-06-22 13-12-20
Screenshot from 2019-06-22 13-12-28

**Comment by mundane140** [comment]
This should suffice if the data about volunteer is:
A profile picture
A name
Social media links

Its really basic layout with hover animations on links.

**Comment by mundane140** [comment]
Open to suggestions

**Comment by mundane140** [comment]
@hellozee

**Comment by hellozee** [comment]
Nice, I guess the best way would be, merge this into a separate branch and let every volunteer add his/her detail

**Comment by mundane140** [comment]
Hey, I think I have made necessary modifications. Lemme know if you need anything else.
@hellozee

**Comment by hellozee** [comment]
@mundane140 gimme a few days, kind of in between something, :)

**Comment by mundane140** [comment]
Roger

**Pull request closed without merging**
